version: '3.8'
services:
  dev-db:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - video-service
networks:
  video-service: